DOMAIN = "ha_battery_status_monitor"

CONF_DEVICE_IDS = "device_ids"
CONF_WARNING_THRESHOLD = "warning_threshold"
CONF_CRITICAL_THRESHOLD = "critical_threshold"

DEFAULT_WARNING_THRESHOLD = 20
DEFAULT_CRITICAL_THRESHOLD = 10
DEFAULT_SCAN_INTERVAL = 30

STATUS_NORMAL = "normal"
STATUS_WEAK = "weak"
STATUS_CRITICAL = "critical"
STATUS_UNAVAILABLE = "unavailable"

STATUS_ORDER = (
    STATUS_CRITICAL,
    STATUS_WEAK,
    STATUS_UNAVAILABLE,
    STATUS_NORMAL,
)
